const config = {
  faq: {
    name: 'faq',
    category: 'gateway_product',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_admin: {
    name: 'mod_admin',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_admin_menu: {
    name: 'mod_admin_menu',
    category: 'tools',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_admin_passwords: {
    name: 'mod_admin_passwords',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_api_accesskeys: {
    name: 'mod_api_accesskeys',
    category: 'tools',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_capability_category: {
    name: 'mod_capability_category',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_capability_master: {
    name: 'mod_capability_master',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_city: {
    name: 'mod_city',
    category: 'region',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_country: {
    name: 'mod_country',
    category: 'region',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_customer: {
    name: 'mod_customer',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_db_changelog: {
    name: 'mod_db_changelog',
    category: 'logs',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_email_notifications: {
    name: 'mod_email_notifications',
    category: 'logs',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_email_notify_template: {
    name: 'mod_email_notify_template',
    category: 'resources',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_group_master: {
    name: 'mod_group_master',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_log_history: {
    name: 'mod_log_history',
    category: 'user',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_notify_operation_values: {
    name: 'mod_notify_operation_values',
    category: 'job',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_notify_schedule: {
    name: 'mod_notify_schedule',
    category: 'job',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_page_settings: {
    name: 'mod_page_settings',
    category: 'resources',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_push_notifications: {
    name: 'mod_push_notifications',
    category: 'logs',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_push_notify_template: {
    name: 'mod_push_notify_template',
    category: 'resources',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_setting: {
    name: 'mod_setting',
    category: 'tools',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_sms_notifications: {
    name: 'mod_sms_notifications',
    category: 'logs',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_sms_notify_template: {
    name: 'mod_sms_notify_template',
    category: 'resources',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  mod_state: {
    name: 'mod_state',
    category: 'region',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  products: {
    name: 'products',
    category: 'gateway_product',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  product_category: {
    name: 'product_category',
    category: 'gateway_product',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  product_reviews: {
    name: 'product_reviews',
    category: 'gateway_product',
    primary_key: 'id',
    soft_delete: false,
    audit_log: false,
  },
  user: {
    name: 'user',
    category: 'gateway_user',
    primary_key: 'iUserId',
    soft_delete: false,
    audit_log: false,
  },
};

export default config;
